valor = int(input('digite um número: '))
print('-'*8)
print('{}.1 = {:3}'.format(valor, valor*1))
print('{}.2 = {:3}'.format(valor, valor*2))
print('{}.3 = {:3}'.format(valor, valor*3))
print('{}.4 = {:3}'.format(valor, valor*4))
print('{}.5 = {:3}'.format(valor, valor*5))
print('{}.6 = {:3}'.format(valor, valor*6))
print('{}.7 = {:3}'.format(valor, valor*7))
print('{}.8 = {:3}'.format(valor, valor*8))
print('{}.9 = {:3}'.format(valor, valor*9))
print('{}.10 = {:3}'.format(valor, valor*10))
print('-'*8)