x = input('digite algo: ')
print('é do tipo ',type(x))
print('é alfa numérico? ', x.isalnum())
print('é número? ', x.isnumeric())
print('é decimal? ', x.isdecimal())
print('é maiúsculo? ', x.isupper())
print('é minúsculo? ', x.islower())
print('é só espaços? ', x.isspace())
